language: python

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    update: true
    packages:
    - python-dbus
    - python-lxml
    - python-gi
    - python-gobject-2

script:
  - dbus-launch python test/test_localsettings.py
